[workspace]
resolver = "3" # Use the modern resolver

members = [
    "spreadsheet_client",
    "spreadsheet_core",
    "spreadsheet_server",
]

# This tells Shuttle which package to deploy
[workspace.metadata.shuttle]
name = "spreadsheet_server"